version: '2.1'
services:
#  mongodb-server:
#    image: mongo:3.4.10-jessie
#    expose:
#      - "27017"
#
#  redis-server:
#    image: redis:3.2.9-alpine
#    expose:
#      - "6379"
#
#  mysql-server:
#    image: mysql:5.6
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=test
#    expose:
#      - "3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping","--silent"]
#      interval: 5s
#      timeout: 10s
#      retries: 5
#
#  zookeeper-server:
#    image: zookeeper:3.4.9
#    expose:
#      - "2181"
#    ports:
#      - "2181:2181"
#    healthcheck:
#      test: ["CMD", "/zookeeper-3.4.9/bin/zkServer.sh", "status"]
#      interval: 10s
#      timeout: 10s
#      retries: 5

  skywalking-agent:
    image: skywalking/skywalking-agent:3.2.4-2017

  cache-server:
    image: skywalking/test-cache-server:3.2.4-2017
#    links:
#      - "mongodb-server"
#      - "redis-server"
#      - "zookeeper-server"
#    depends_on:
#      zookeeper-server:
#        condition: service_healthy
    environment:
      - MONGO_HOST=mongodb-server
      - REDIS_HOST=redis-server
      - ZK_ADDRESS=zookeeper-server:2181
      - COLLECTOR_SERVERS=skywalking-collector:10800
    volumes_from:
      - skywalking-agent

#  presistence-server:
#    image: skywalking/test-persistence-server:3.2.4-2017
#    links:
#      - "mysql-server"
#      - "zookeeper-server"
#    depends_on:
#      mysql-server:
#        condition: service_healthy
#    environment:
#      - MYSQL_ADDRESS=mysql-server:3306
#      - ZK_ADDRESS=zookeeper-server:2181
#
#  portal-service:
#    image: skywalking/test-portal:3.2.4-2017
#    expose:
#      - 8080
#    ports:
#      - "8080:8080"
#    links:
#      - "presistence-server"
#      - "cache-server"
#    environment:
#      - ZK_ADDRESS=zookeeper-server:2181
